name: Deploy Model

on:
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy mlflow Model
      run: | 
        az ml online-endpoint create --name diabetes-mlflow-mahi  --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops -f src/create-endpoint.yml
        az ml online-deployment create --name mlflow-deployment-mahi --endpoint diabetes-mlflow  --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops -f src/deployment.yml --all-traffic
