name: Trigger Machine Learning Job with Pull Request

on: 
  push

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning Job
      run: | 
       az ml job create --file src/job.yml --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
