name: Unit Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install pytest and required modules
      run: |
        python -m pip install pytest
        python -m pip install model
    - name: Run unit tests
      run: | 
        python tests/test_train.py
