name: Unit Test

on:
  pull_request

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install pytest and required modules
      run: |
        python -m pip install pytest
        python -m pip install mlflow
        python -m pip install scikit-learn
    - name: Run unit tests
      run: | 
        pytest tests/test_train.py
